version: "3.8"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  environment:
   - MYSQL_ROOT_PASSWORD=rootpassword
   - MYSQL_DATABASE=achat_db
  ports:
   - 3306:3306
  volumes:
   - db:/var/lib/mysql

 app-achat:
  depends_on:
   - mysqldb
  image: syrinelouati/achat:1.0.0
  restart: on-failure
  ports:
   - 8089:8089
   - 1234:1234  # Expose metrics endpoint
  environment:
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achat_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "rootpassword",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
  stdin_open: true
  tty: true

 prometheus:
  image: prom/prometheus:latest
  volumes:
   - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
   - "9091:9090"
  restart: unless-stopped

 grafana:
  image: grafana/grafana:latest
  ports:
   - "3001:3000"
  restart: unless-stopped
  volumes:
   - grafana-storage:/var/lib/grafana

volumes:
 db:
 grafana-storage:
