version: "3.8"
services:
 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=achatdb
  ports:
   - 3306:3306
  volumes:
   - db:/var/lib/mysql

 app-achat:
  depends_on:
   - mysqldb
  image: syrinelouati/achat:1.0.0
  restart: on-failure
  ports:
   - 8082:8082
   - 1234:1234
  environment:
   SPRING_APPLICATION_JSON: '{
        "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
  stdin_open: true
  tty: true

 prometheus:
  image: prom/prometheus:latest
  volumes:
   - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
   - "9091:9091"
  restart: unless-stopped

 grafana:
  image: grafana/grafana:latest
  ports:
   - "3001:3001"
  restart: unless-stopped
  volumes:
   - grafana-storage:/var/lib/grafana

volumes:
 db:
 grafana-storage:
